services:
  - type: web
    name: steelcutoptimizer-backend
    env: docker  # Sử dụng Docker
    dockerfilePath: ./Dockerfile  # Đường dẫn đến Dockerfile
    region: singapore
    plan: free
    branch: main
    rootDir: .
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: SESSION_SECRET
        value: tlu-steel-cutting-app-secret
      - key: NODE_ENV
        value: production

  - type: web
    name: steelcutoptimizer-frontend
    env: static
    plan: free
    branch: main
    rootDir: client
    buildCommand: npm install && npm run build:client
    staticPublishPath: dist/public
    envVars:
      - key: NODE_VERSION
        value: 18